update GoodsInventory,GoodsInfo set GoodsInventory.onSell=1 where GoodsInfo.id=GoodsInventory.goodsId and GoodsInfo.imageUrl is not null;
update GoodsInfo set middlePackNum = mod(id,23)+1;
update GoodsInventory,GoodsInfo set GoodsInventory.isSplit = true where GoodsInfo.middlePackNum > 13 and GoodsInventory.goodsId = GoodsInfo.id;
update GoodsInventory,GoodsInfo set GoodsInfo.negSell = 1 where GoodsInfo.middlePackNum > 12 and GoodsInventory.goodsId = GoodsInfo.id;
update GoodsPrice,GoodsInventory set GoodsPrice.wholesalePrice = GoodsPrice.refRetailPrice + 0.05,GoodsPrice.price1 = GoodsPrice.refRetailPrice + 0.01,GoodsPrice.price2 = GoodsPrice.refRetailPrice + 0.02,GoodsPrice.price3 = GoodsPrice.refRetailPrice + 0.03 where GoodsInventory.onSell = 1 and GoodsPrice.goodsId = GoodsInventory.goodsId ;
delete from GoodsTypeMap;
insert into GoodsTypeMap(goodsTypeId, goodsId, isMain) select MOD(id,180),id,true from GoodsInfo;
update GoodsGsp set isPrescriptionDrugs = 1 where mod(GoodsGsp.goodsId,8)=1;
update GoodsGsp set isMedicalInsuranceDrugs = 1 where mod(GoodsGsp.goodsId,8)=2;
update GoodsGsp set isNationalMedicine = 1 where mod(GoodsGsp.goodsId,8)=3;
update GoodsGsp set isPrescriptionDrugs = 1,isMedicalInsuranceDrugs = 1 where mod(GoodsGsp.goodsId,8)=4;
update GoodsGsp set isPrescriptionDrugs = 1,isNationalMedicine = 1 where mod(GoodsGsp.goodsId,8)=5;
update GoodsGsp set isMedicalInsuranceDrugs = 1,isNationalMedicine = 1 where mod(GoodsGsp.goodsId,8)=6;
update GoodsGsp set isMedicalInsuranceDrugs = 1,isNationalMedicine = 1,isPrescriptionDrugs = 1 where mod(GoodsGsp.goodsId,8)=7;